'use client'

import React, { useState, useCallback, useEffect } from 'react'
import { motion } from 'framer-motion'
import { GlassCard } from '@/components/GlassCard'
import { MagneticButton } from '@/components/MagneticButton'
import { WaveformVisualizer } from '@/components/WaveformVisualizer'
import { api } from '@/lib/api'
import { useAuth } from '@/hooks/useAuth'
import { 
  Upload, 
  FileCode2, 
  Sparkles, 
  Download, 
  Copy, 
  Check,
  Terminal,
  FileText,
  Maximize2,
  Minimize2,
  Loader2
} from 'lucide-react'
import { cn } from '@/lib/utils'

interface UploadedFile {
  name: string
  size: number
  content: string
  language: string
}

interface JobStatus {
  id: string
  step: string
  content: string
  complete: boolean
}

export default function DocumentationPage() {
  const [files, setFiles] = useState<UploadedFile[]>([])
  const [isDragging, setIsDragging] = useState(false)
  const [generatedDocs, setGeneratedDocs] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [focusMode, setFocusMode] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(true)
  }, [])

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
  }, [])

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
    
    const droppedFiles = Array.from(e.dataTransfer.files)
    handleFiles(droppedFiles)
  }, [])

  const handleFiles = (fileList: File[]) => {
    fileList.forEach(file => {
      if (file.name.match(/\.(py|js|ts|jsx|tsx|java|c|cpp|cs|go|rs|php|rb|swift|kt)$/)) {
        const reader = new FileReader()
        reader.onload = (e) => {
          const content = e.target?.result as string
          setFiles(prev => [...prev, {
            name: file.name,
            size: file.size,
            content,
            language: getLanguageFromExtension(file.name)
          }])
        }
        reader.readAsText(file)
      }
    })
  }

  const getLanguageFromExtension = (filename: string): string => {
    const ext = filename.split('.').pop()?.toLowerCase()
    const langMap: Record<string, string> = {
      py: 'python', js: 'javascript', ts: 'typescript',
      jsx: 'jsx', tsx: 'tsx', java: 'java',
      c: 'c', cpp: 'cpp', cs: 'csharp',
      go: 'go', rs: 'rust', php: 'php',
      rb: 'ruby', swift: 'swift', kt: 'kotlin'
    }
    return langMap[ext || ''] || 'text'
  }

  const generateDocumentation = async () => {
    if (files.length === 0) return
    
    setIsGenerating(true)
    setGeneratedDocs('')
    
    // Simulate streaming response
    const sampleDoc = `# ${files[0].name.replace(/\.[^/.]+$/, '')} Documentation

## Overview
This module provides core functionality for data processing and analysis.

## Functions

### main()
Entry point for the application. Handles initialization and orchestration.

\`\`\`${files[0].language}
def main():
    """Initialize and run the application."""
    pass
\`\`\`

## API Reference

| Method | Description | Parameters |
|--------|-------------|------------|
| init() | Initialize system | config: dict |
| run() | Execute process | input: str |

---
*Generated by Tekshila AI • ${new Date().toLocaleDateString()}*`

    // Stream characters
    for (let i = 0; i < sampleDoc.length; i++) {
      await new Promise(resolve => setTimeout(resolve, 10))
      setGeneratedDocs(prev => prev + sampleDoc[i])
    }
    
    setIsGenerating(false)
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedDocs)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadDocumentation = () => {
    const blob = new Blob([generatedDocs], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'README.md'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className={cn('space-y-8', focusMode && 'focus-mode-active')}>
      {/* Header */}
      <div className="flex items-center justify-between dimmable">
        <div>
          <span className="micro-label text-crimson mb-2 block">DOCUMENTATION ENGINE</span>
          <h1 className="headline-display text-3xl">Generate Documentation</h1>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => setFocusMode(!focusMode)}
            className={cn(
              'p-2 rounded-lg border transition-all',
              focusMode 
                ? 'bg-crimson/20 border-crimson text-crimson' 
                : 'border-glass-stroke text-silver-400 hover:text-silver-200'
            )}
            aria-label={focusMode ? 'Exit focus mode' : 'Enter focus mode'}
          >
            {focusMode ? <Minimize2 className="w-5 h-5" /> : <Maximize2 className="w-5 h-5" />}
          </button>
        </div>
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Panel - Upload */}
        <div className="dimmable">
          <GlassCard spotlight className="p-6 h-full">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-lg bg-crimson/10">
                <FileCode2 className="w-5 h-5 text-crimson" />
              </div>
              <div>
                <h2 className="font-display font-semibold text-lg">Source Code</h2>
                <p className="text-sm text-silver-500">Upload or drop your files</p>
              </div>
            </div>

            {/* Upload Zone */}
            <div
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              className={cn(
                'border-2 border-dashed rounded-xl p-8 text-center transition-all duration-300',
                isDragging 
                  ? 'border-crimson bg-crimson/5' 
                  : 'border-glass-stroke hover:border-silver-600'
              )}
            >
              <Upload className="w-10 h-10 text-silver-500 mx-auto mb-4" />
              <p className="font-ui text-silver-300 mb-2">
                Drop files here or click to browse
              </p>
              <p className="text-sm text-silver-500">
                Supports Python, JavaScript, TypeScript, Java, C++, and more
              </p>
              <input
                type="file"
                multiple
                accept=".py,.js,.jsx,.ts,.tsx,.java,.c,.cpp,.cs,.go,.rs,.php,.rb,.swift,.kt"
                onChange={(e) => e.target.files && handleFiles(Array.from(e.target.files))}
                className="hidden"
                id="file-upload"
              />
              <label htmlFor="file-upload">
                <MagneticButton variant="secondary" size="sm" className="mt-4">
                  Select Files
                </MagneticButton>
              </label>
            </div>

            {/* File List */}
            {files.length > 0 && (
              <div className="mt-6 space-y-2">
                <span className="micro-label text-silver-500">UPLOADED FILES</span>
                {files.map((file, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="flex items-center gap-3 p-3 rounded-lg bg-surface/50 border border-glass-stroke"
                  >
                    <Terminal className="w-4 h-4 text-silver-400" />
                    <span className="font-mono text-sm text-silver-300 flex-1">{file.name}</span>
                    <span className="text-xs text-silver-500">{(file.size / 1024).toFixed(1)} KB</span>
                  </motion.div>
                ))}
              </div>
            )}

            {/* Generate Button */}
            {files.length > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="mt-6"
              >
                <MagneticButton 
                  className="w-full" 
                  onClick={generateDocumentation}
                  disabled={isGenerating}
                >
                  <span className="flex items-center justify-center gap-2">
                    {isGenerating ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                        Analyzing...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4" />
                        Generate Documentation
                      </>
                    )}
                  </span>
                </MagneticButton>
              </motion.div>
            )}
          </GlassCard>
        </div>

        {/* Right Panel - Output */}
        <div className={cn('dimmable', focusMode && 'focused')}>
          <GlassCard spotlight className="p-6 h-full flex flex-col">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-crimson/10">
                  <FileText className="w-5 h-5 text-crimson" />
                </div>
                <div>
                  <h2 className="font-display font-semibold text-lg">Documentation</h2>
                  <p className="text-sm text-silver-500">
                    {isGenerating ? 'Generating...' : generatedDocs ? 'Ready' : 'Waiting for input'}
                  </p>
                </div>
              </div>
              
              {generatedDocs && (
                <div className="flex items-center gap-2">
                  <button
                    onClick={copyToClipboard}
                    className="p-2 rounded-lg hover:bg-white/5 transition-colors text-silver-400 hover:text-silver-200"
                    aria-label="Copy to clipboard"
                  >
                    {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                  </button>
                  <button
                    onClick={downloadDocumentation}
                    className="p-2 rounded-lg hover:bg-white/5 transition-colors text-silver-400 hover:text-silver-200"
                    aria-label="Download"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </div>
              )}
            </div>

            {/* Output Area */}
            <div className="flex-1 min-h-[400px] rounded-xl bg-surface/80 border border-glass-stroke p-4 overflow-auto">
              {generatedDocs ? (
                <pre className="font-mono text-sm text-silver-300 whitespace-pre-wrap leading-relaxed">
                  {generatedDocs}
                  {isGenerating && (
                    <span className="inline-block w-2 h-4 bg-crimson ml-1 animate-pulse" />
                  )}
                </pre>
              ) : (
                <div className="h-full flex flex-col items-center justify-center text-silver-500">
                  <Sparkles className="w-12 h-12 mb-4 opacity-50" />
                  <p className="font-ui">Upload code to generate documentation</p>
                </div>
              )}
            </div>
          </GlassCard>
        </div>
      </div>
    </div>
  )
}
